package app

import (
	"fmt"

	"github.com/andrewarrow/feedback/router"
)

func handleDemo(c *router.Context) {
	link := map[string]any{}
	link["link"] = "https://youtu.be/wh_M25S2xUw"
	send := map[string]any{}
	send["item"] = link
	send["summaries"] = summaryLookup
	count := []string{}
	for i := 0; i < 55; i++ {
		count = append(count, fmt.Sprintf("%d", i))
	}
	send["count"] = count
	c.SendContentInLayout("demo.html", send, 200)
}

func handleDemoPoll(c *router.Context) {
	key := c.Request.URL.Query().Get("key")
	m := map[string]any{}
	if key == "summaries" {
		c.SendContentAsJson(summaryLookup, 200)
		return
	}
	s := lookup[key]
	if len(s) > 36 {
		s = s[0:36] + "..."
	}
	m["stt"] = s
	c.SendContentAsJson(m, 200)
}

var summaryLookup = map[string]string{
	"0":  "HRV did not exist; the speaker discusses HRV (Heart Rate Variability), a metric initially used to predict newborn health, which later linked to various clinical conditions and wellness goals.",
	"1":  "HRV (Heart Rate Variability) measures the oscillatory variability in milliseconds between each heartbeat, a technical definition that aims to understand greater health and resilience.",
	"2":  "Variations in heart rhythm, known as resonance sinus arrhythmia, must be optimized for resilience, adaptability, and flexibility to effectively respond and acclimate to stressors.",
	"3":  "HRV measures individual resilience, amplifying factors, and natural gifts, providing insights through calibrated breathing and research, while also addressing the unknown benefits of lower HRV during stress.",
	"4":  "The Reptilian response mobilizes the body to conserve energy, but in modern times it often persists longer than needed, whereas a high Heart Rate Variability (HRV) would have been essential for reptiles to regain energy.",
	"5":  "The nervous system, under stress, fragments \"auten IC bandwidth\" to conserve energy, potentially adapting to a dynamic environment by prioritizing specific frequencies or functions over others.",
	"6":  "Reduced response ability arises from prolonged rumination on stressors, extending stress beyond conscious control; instead, physiological constructs like heart rate variability training may help learn to let go.",
	"7":  "The range of HRV is influenced by biological factors and underlying conditions, including chronic stress, and it's pointless to compare HRV scores with others, as individual limits and goals vary.",
	"8":  "Individuals with heightened physiological sensitivity, or \"physiologically gifted\" people, have a natural increased heart rate reactivity to stress, which can be influenced by factors such as caffeine intake or other underlying conditions.",
	"9":  "Chris discusses variables affecting nerve sensitivity, including sleep, alcohol, exercise, and stress, which can impact HIV, and describes the experiential feel of low heart rate variability (HRV).",
	"10": "Athletes develop somatic awareness by recognizing when their heart rate (HR) is lower or higher than usual upon waking, as perceived physical sensations and emotional states vary depending on individual HR heart rate variability (HRV).",
	"11": "The relationship between heart rate variability, autonomic flexibility, and brain function allows for flexible responses to changing needs, adapting to stress rather than simply being calm or relaxed.",
	"12": "Researchers have studied heart rate variability's impact on cognitive dexterity, discovering a link between oscillations in heart rate and brain function, demonstrating flexible thinking and focus.",
	"13": "The ability to pause before reacting and consider multiple factors is a key cognitive benefit of heart rate variability, particularly the ability to inhibit impulsive thoughts and emotions.",
	"14": "HRV impacts cognitive process and autonomic flexibility, with healthier hearts typically having higher HRV, which is correlated with a lower risk of cardiovascular conditions.",
	"15": "The speaker wants a heart to have large and abundant oscillations, essentially desiring its vital functions to operate with great flexibility and movement.",
	"16": "HRV has two distinct pathways: short-term hacking for immediate results vs. long-term training for improved autonomic nervous system flexibility, leading to flexible responses to life's demands.",
	"17": "Optimizing the nervous system through resonant frequency breathing can increase baroreflex gain and precision in sensing and responding to stimuli, transforming one into a more agile and responsive system.",
	"18": "The text describes how expanding energy and strengthening the parasympathetic nervous system allows for quicker relaxation and calmness in response to stressors, enabling more effective management of daily stressors like email overload.",
	"19": "The nervous system becomes more precise as you process emails, reducing stress and allowing for increased flexibility, agility, and adaptability with HRV training and wearable calibration.",
	"20": "Understanding individual responses to variables requires personalized tracking and calibration to identify what works for each person, as variables affect people differently.",
	"21": "Researchers at UMDNJ discovered residents sinus arrhythmia, a 0.1 Hertz frequency that awakens the entire nervous system, engaging brain-heart-digestive tract pathways, strengthening homeostatic regulatory mechanisms.",
	"22": "The text discusses using a technique to treat various health conditions, including anxiety and depression, and its application in optimizing athletic performance by gaining control over anxiety and heart rate oscillations.",
	"23": "Maximizing baseline heart rate variability through 15-minute daily practices for 4 weeks, followed by stress management protocol to oscillate between sympathetic and parasympathetic states.",
	"24": "The individual is trained to enter a parasympathetic state to improve focus and learning, tailored to their specific needs through modulation of physiological states and behavior.",
	"25": "Practice specific breathing paces (15min morning and evening, 4 weeks to dial in rate) can amplify or worsen heart rate variability, with initial sessions focusing on identifying resonant frequency (5-6.5 breaths per minute) and abdominal breathing.",
	"26": "The Pacer app helps optimize oxygen and blood flow to the brain's prefrontal lobe, enhancing cognitive abilities by synchronizing breathing with a visual cue, such as a rising and falling line on a screen.",
	"27": "Watching the Pacer for 15 minutes twice a day can affect cognitive impact, but it takes unknown time to alter breath rate, which requires 30 minutes of training to reprogram.",
	"28": "The protocol focuses on training the heart to resonate at a specific frequency, which becomes the new baseline, and breath training begins after 7-8 weeks, aiming to maintain gains after completing the 10-12 week program.",
	"29": "Regular breathing exercises, like calf raises, can help develop mental clarity, and while frequency varies among individuals, it's recommended to maintain breathing exercises at least 3-4 times a week for 15 minutes.",
	"30": "Clients learn to titrate deep breathing for 15 minutes twice a day based on their needs, adapting throughout the day to manage anxiety and maintain overall well-being.",
	"31": "Practicing the Power 5 technique involves focusing on breathing, inhaling fresh air and exhaling fear/anxiety to reset, with potential applications in parenthood and stress management.",
	"32": "Professional athletes often struggle with racing minds, using techniques like breathing and counting to clear their minds and return to a baseline state.",
	"33": "Counting while breath-counting during meditation is challenging due to the same brain area being used, causing loss of focus and account keeping, making it difficult to maintain attention.",
	"34": "For some, Power 5 is used to manage anxiety or fast heart rate, while others use it as a daily reminder to remain centered, pairing it with habitual activities like eating or taking moments to breathe.",
	"35": "Research shows nasal breathing can positively impact HRV, and a facial strategy of inhaling through the nose and exhaling through the mouth can optimize HRV training.",
	"36": "North maximizes HRV, but often inhaling/exhaling through nose leads to increased HIV risk, and each individual's nervous system requires nuanced approaches to achieve optimal breathing.",
	"37": "Nasal breathing produces greater HRV gains than nasal inhale/mouth exhale, also enhances peak expiratory flow, and may contribute to increased endurance without changes in training.",
	"38": "The HRV training process helps individuals, regardless of their profession or skill level, maximize their potential by reducing performance anxiety and consistently staying at their maximum talent and ability.",
	"39": "The speaker asks about the relative effect of increasing VO2 max through fitness training versus resonant breathing practices, noting that while both work well together, only resonant breathing can develop a reflex to unconsciously modulate stress.",
	"40": "The effectiveness of low-intensity training vs. VO2 max training for improving heart rate variability and cardiovascular fitness is debated, with research suggesting benefits for both approaches.",
	"41": "The speaker advises physical training integration for specific outcomes, collaborating with athletic trainers to analyze data, and has observed reliable improvements in performance from certain protocols.",
	"42": "The speaker discusses how measuring HRV can be insightful, notes improvements in HRV due to acupuncture, and shares examples of unexpected benefits from energy healing on actors' heart rate variability.",
	"43": "People access their parasympathetic state more easily with supplements, such as Lima, which has antioxidant and anti-anxiety effects, and may improve sleep, according to anecdotal reports and measured improvements in clients.",
	"44": "Researchers use heart rate variability (HRV) to measure the effectiveness of interventions on the autonomic nervous system, noting that nocturnal HRV is a reliable method due to minimal movement and variables at night.",
	"45": "Wearable data may be skewed by various stressors or behaviors, and even unusual results can lead to understanding with proper collection and analysis.",
	"46": "Wearables' HRV readings can be skewed by sleeping position and wakefulness, making continuous monitoring challenging, with a potential solution being a device that takes a snapshot upon waking.",
	"47": "The speaker recommends Polar straps for heart rate variability measurement, citing their scientific reliability, ease of use, and ability to track HRV in real-time and during sleep, with optional phone app downloads.",
	"48": "Practicing sounds, such as sound baths, can increase heart rate variability and induce an ideal performance state, while also activating the parasympathetic nervous system.",
	"49": "Understand and measure individual responses to amplify or detract from elite selves, align with goals, and prioritize calibration of autonomic nervous system, especially heart rate variability (HRV), before implementing interventions.",
	"50": "Training HRV with resonant frequency for 10-12 weeks, 15 minutes twice a day, optimizes heart rate variability and modulatory mechanisms, but may not work for everyone, including those who don't commit to the full program.",
	"51": "HRV training requires detective work to understand why someone isn't responding, often revealing physiological stress, overtraining, or lack of recovery, which can be addressed and resolved for effective training.",
	"52": "Common errors in breathing include frequency and rate misalignment, and excessive pressure and perfectionism can compromise the effectiveness of breathing exercises.",
	"53": "Trying to rewire the nervous system to be safe and flexible, which can enhance decision-making, despite potential top-down interference, especially in PTSD patients, but persistence is key.",
	"54": "Pairing a safe feeling with a memory can help access physiological imprints, even in times of stress, by connecting to a sense of safety and letting go of the rest of the world.",
}
var lookup = map[string]string{
	"0_0":  "what's the history of HIV who who discovered it  no it's really interesting it originated  being a metric that  doctors looked at before babies were born",
	"0_1":  "to predict the Vitality of the of the unborn baby that they would be healthy upon birth  and then in time doctors began using it as a metric,",
	"0_2":  "of cardiovascular health and other conditions uh HRV is very much associated with  clinical conditions from,",
	"0_3":  "from myalgia to irritable bowel syndrome to depression to anxiety and then a cohort a small subset of people including myself came along",
	"0_4":  "principal what about people that aren't afflicted by a condition but just wanted to get better  and and that question has been the last 17",
	"0_5":  "years of my research in practice  wow so I think a lot of people listening will be familiar with HRV what it is and sort of the the the fundamental",
	"1_0":  "but just give us a 30000 foot overview recap  sure  so HRV  has to do with the variability in between each heart",
	"1_1":  "potentially the short simple answer without getting too Technical and I think that's 1 of the things the public has to understand people get lost in the science Chris is",
	"1_2":  "that we are looking for bigger numbers for greater health and resilience but everybody has a range and and so the scientific",
	"1_3":  "definition has to do with the oscillatory variability in between each heartbeat um and it measured in milliseconds and",
	"1_4":  "that's the technical definition what we'll talk about today is HRV in terms of RSA resonance sinus arrhythmia and it's so much easier to understand and grasp as a user",
	"1_5":  "because you can look at with all sorts of different wearables that are out now the peak to trough so when you inhale your heart rate goes up and when you exhale",
	"2_0":  "it goes down and that phenomenon is known as resonance sinus arrhythmia and ultimately we want that variation to be as big and beautiful as possible almost",
	"2_1":  "looks like ocean like waves but that's not exactly what happens in life  we get stuck there are stressors and and we can talk about",
	"2_2":  "different variables in time but we want to optimize those oscillations to be resilient adaptable flexible um marked by",
	"2_3":  "agility  to to kind of respond as we need an acclimate flexibly is that what you mean by autonomic flexibility it does",
	"2_4":  "with us and people think about stress in terms of am I stressed or am I not but what we really should be talking about",
	"2_5":  "is your agility and handling it how long does it last are you able to let it go when it happens how long does it take You Are there specific",
	"3_0":  "thrusters that take you longer and you begin to look at HIV and we can dive into this as deeply as you want but as a metric",
	"3_1":  "that gives you insights about yourself so of course we can train HRV and it'll take you through my protocol for doing that which is in my book heart breathe mind but but I want the world to",
	"3_2":  "understand HRV is a measure of who they are what amplifies them what takes away from their natural gifts and it's it's a metric that",
	"3_3":  "people can calibrate with breathing but also with study and research on on what kind of leads to these changes",
	"3_4":  "intraday I have never heard anybody explain  the Adaptive reason for why HRV lowers when we are stressed",
	"3_5":  "there must be an advantage that is given to the user for having a lower HRV under sympathetic arousal what is that",
	"4_0":  "it's likely associated with The Reptilian response of a mobilization our body mobilizes even in prehistoric  days to conserve",
	"4_1":  "energy and while The Reptilian response served a function and can serve a function in certain stress situations usually it doesn't",
	"4_2":  "and it stays longer than we need so  that's so interesting so  your hypothesis",
	"4_3":  "is that  when we were reptiles we would need to  but why surely surely a high HRV if we needed to uh lay out in the",
	"4_4":  "sun and warm ourselves on a rock surely that would have allowed us to regain more energy than a low HRV know  that would",
	"4_5":  "Lang lying on a rock and being in the sun  the sun Sunshine the light exposure is is what could enhance HRV but the autonomic",
	"5_0":  "nervous system during times of stress wants to conserve energy and um and what it tends to do is fragment what I call auten",
	"5_1":  "IC bandwidth so if you have an HRV Chris let's say just you measure it with your order ring or or other wearables and there are many and you have a range of 4",
	"5_2":  "2 to 75 you begin to look at what's happening on different days to understand what's what's reducing your HRV and make",
	"5_3":  "it seems too late maybe it's a conflict with a a good friend but what you're asking me is how could this have been adaptive for us",
	"5_4":  "um and my hypothesis would be in in terms of trying to  conserve  energy and and somehow",
	"5_5":  "the body safe in that way however we're in such a dynamic world that if if we're a fraction of ourselves and and the flex",
	"6_0":  "ability to respond is reduced it doesn't work out that way  because we ruminate on the stressor for so long that we actually extend the stressor for a good amount of time",
	"6_1":  "yes and that for most people is beyond conscious control so the idea of Just Let It Go is is  great great",
	"6_2":  "idea but then how do you do it and I would argue that letting go is much more a physiological construct  that that can be taught",
	"6_3":  "through processes such as heart rate variability biofeedback training then then just and I'm a psychologist by trade then then just cognitive techniques but",
	"6_4":  "first you have to teach the autonomic nervous system how to let go right so you're suggesting that we go bottom up from the body to the mind as opposed to top down from the",
	"6_5":  "saying hey calm down you're being too stressed why can't you just let go of this thing which often makes you more stressed so the other the other question that I have what determines our range you've mentioned",
	"7_0":  "that we have a range within which we sit I know that 1 of your prescriptions will be your goal is to get to the top end of your range so therefore comparing your HRV with somebody else's",
	"7_1":  "is kind of pointless unfortunately I'm in I'm in a a whoop group with some pro athletes some cricketers and some of their hrvs are in the 200s so I",
	"7_2":  "I'm always going to be  bottom of the pile uh around them but what is it that determines our range  there are a",
	"7_3":  "to the factors there are biological um  cases to this and and low HRV um in some",
	"7_4":  "cases can indicate a clinical condition and um and they had that happen with clients where we've uncovered and properly gotten treatment and then and then worked",
	"7_5":  "amplifying HIV is they went through through other treatments but it also can be chronic stress that's not properly managed it can be a host of different pieces",
	"8_0":  "there are also people that are more sensitive in this world and there are people that feel deeply they connect quickly I call them physiologically gifted that in stressful moment",
	"8_1":  "comments their heart rate reactivity May jump 30 beats whereas someone else may jump 10 and that's not conscious and that's not something that talk therapy is going",
	"8_2":  "to change but they can increase the Precision of their their response under stress by having a stronger what's called um",
	"8_3":  "Bearer reflex gain through this process the bearer receptors control heart rate and blood pressure and we gain control over that reactivity in the moment it's",
	"8_4":  "it just calms and um with that said there are  many many different reasons people have different levels of HR",
	"8_5":  "I had 1 person it took us 3 sessions I mean questions after questions I got it they were drinking 19 cups of coffee a day so sometimes the",
	"9_0":  "variables Chris are internal sometimes they're medical and sometimes they're external a big  variable that people think about conscious",
	"9_1":  "lie  that having a few glasses of alcohol they know it impacts them but they don't really have a sense of how sensitive their nervous system is",
	"9_2":  "or how long it lasts but you can measure that and so factors like sleep alcohol use lack of exercise chronic stress can certain",
	"9_3":  "Li dampen HIV but they're not the only reasons  what does low HRV feel like  experientially if it's",
	"9_4":  "uh acute let's say that you could just throw low HRV at someone that's listening now what would that feel like in their body and their mind",
	"9_5":  "someone can't identify low HRV if if that's their General Baseline state but some people can and we and we actually some",
	"10_0": "times train lists um from from my clinic with clients that are athletes on being able to recognize when when they have a lower HR",
	"10_1": "than a higher HRV when they wake up before they look at their scores just to develop their sense of somatic awareness and and being just aware of what their body",
	"10_2": "telling them um  some people will say when they are their HRV is on the lower end of the range that they",
	"10_3": "they feel more myopic meaning their mind gets stuck more more irritable they're less able to control their reactivity and they speed up faster but it's it's really",
	"10_4": "print for each person and what's so fascinating is there's no 1 size fits all uh composite HRV this is",
	"10_5": "is exactly how you'll feel in low HV versus high HV it's about really understanding the person helping them be aware what it feels like for them at the lower HRV and",
	"11_0": "what it feels like at higher HIV and then understanding the factors that they can control um to continue to amplify their HRV",
	"11_1": "talk to me about the relationship between HRV autonomic flexibility and the brain and brain function  so we used to think of",
	"11_2": "what it feels like at higher HIV and then understanding the factors that they can control um to continue to amplify their HRV",
	"11_3": "talk to me about the relationship between HRV autonomic flexibility and the brain and brain function  so we used to think of",
	"11_4": "the heart rate variability just as a metric of the autonomic nervous systems resilience to flexibly respond which means if I need to amp up and run",
	"11_5": "across the street I can this isn't this isn't associated with relaxation or just being calm it's acclimating or adapting flexibly to the needs of the most",
	"12_2": "when you exhale it goes down and we want these oscillations to be as big as possible we also want that oscillatory ability in our in our mind right",
	"12_3": "8 to be able to focus on something deeply and let it go it's a different style of oscillatory  functioning but conceptually the ability to",
	"12_4": "oscillate is what I call cognitive dexterity and we're beginning to understand that heart rate variability is also indicative of someone's cognitive",
	"12_5": "dexterity as well meaning that someone can flexibly alter between kind of deeply dive into",
	"13_2": "is is the ability specifically and it's the first 1 that I work on with people that want the cognitive benefits associated with HRV is inhibition",
	"13_3": "so Chris if there is something and everyone when you really dive deeply and someone's being authentic and open everyone has a place in their life they wish",
	"12_0": "and resilience in the last 10 to 15 years uh myself and several other researchers have focused on heart rate variabilities impact on the",
	"12_1": "and sure enough this concept of oscillation if we think of resonant siosi as that oscillation when you inhale your heart rate goes up",
	"13_0": "diving into a subject matter and then zooming out to consider contextual details or they're able to to consider a lot of",
	"13_1": "information and have a pause before they react so there are different types of of dexterity but what can be really useful",
	"13_4": "they have a little more control over before they act and it could be work it could be partnership it it could also be in a sport",
	"13_5": "performance domain  But ultimately to have the ability to screen out negative thoughts and consider their desired be",
	"14_0": "behavior before they respond becomes a part of the cognitive process that they do gain control over and this",
	"14_1": "process HRV impacts the prefrontal lobe specific  wow what about  so I I understand that HRV is a metric which which",
	"14_2": "is uh both acute and chronic or systemic it's uh an indicator of where you're at now and it's also an indicator of your sort of overall",
	"14_3": "capacity autonomic flexibility probably health and fitness as well uh stress response stuff like that what is the relationship between heart health",
	"14_4": "and HRV to healthier hearts always have a higher bet quote unquote better HRV  yes  in fact there's a  a",
	"14_5": "also research that that suggests that low HRV  is indic is correlated with cardiovascular conditions so we want",
	"15_0": "want that that heart to have those large abundant oscillations um that that very ability is essentially so",
	"15_1": "ated with longevity and and a longer life so when they when I see people go through um in my clinic 12 week training many people",
	"15_2": "people stay for years after they say it's it's not just a change of heart but a change of life and and we go through this process but in the first 12 weeks  we",
	"15_3": "often see the heart rate independent of physical activity dropped 5 beats and so let's say your Baseline heart rate is generally 65",
	"15_4": "it it's now at 60 there is improved cardiovascular efficiency and and certainly that has implications for  heart health and long",
	"15_5": "how do you think about the difference between sort of hacking HRV in the moment so that you get the",
	"16_0": "date change and long-term duration impact on HRV the trait change over time is there a difference between hacking and improving or do all of the hacks",
	"16_1": "that improve in the short-term results in improvements in the long term there it's such a good question and I I I really am so glad you asked because people",
	"16_2": "don't understand that there are 2 different very distinct Pathways for  using HRV and and focusing on",
	"16_3": "HIV for different outcomes so the first 1 is going through a process such as HIV training 10 to 12 weeks to increase heart rate variability at Baseline meaning without even",
	"16_4": "breathing and why would you do that what what does it matter well first of all you want an autonomic nervous system that without even any conscious",
	"16_5": "intervention can flexibly respond to the world so people who are out and about have lots of meetings and go home to a family with with lots of things happening",
	"17_0": "say I just have more energy to to manage the sensory inputs of the World require less from that nervous system because the nervous system",
	"17_1": "system is optimized okay so that's 1 which is optimizing the Baseline how do we do that with the resonant frequency breathing and it it really takes a minimum",
	"17_2": "of 10 weeks 15 minutes a day twice a day breathing at resonant frequency which I'll describe a little bit later but what that does Chris is by week 4",
	"17_3": "you have increased Barrow reflex gain meaning Barrow reflex controls heart rate and blood pressure and you've increased the mechanisms the Precision by which",
	"17_4": "its senses and responds it's just more precise and I say it to my clients it's let's say you you're a Volvo coming into my clinic there's everything's going well you get to where you need to go",
	"17_5": "oh but but now you've you've really increased to being more of a sports car where you can accelerate and decelerate just very quickly with without",
	"18_0": "expended more expended energy so that is the Baseline piece and then within the 10 weeks you continue to strengthen what's called Bearer reflux",
	"18_1": "game and what happens is that the parasympathetic and the sympathetic nervous system and the in stressful situations the sympathetic activation",
	"18_2": "occurs but now your parasympathetic your parasympathetic dominant at Baseline and it comes quicker to bring down the sympathetic the",
	"18_3": "ing is faster and it allows you to let go and this all happens underneath you're not conscious of it but you would just say to me you know",
	"18_4": "let's say Chris 1 of can you give me a stretcher something just  emails emails and what about emails when there's lots of them and I need to reply lots of them",
	"18_5": "so maybe you come in and you say you know the the abundance of emails in every day it is is an 8 out of 10 stressor and",
	"19_0": "as you go through the process the emails don't change the emails have maybe even increased but your reactivity to them the feeling of stress towards",
	"19_1": "them goes down a few numbers and that has to do with the nervous system becoming more precise in your responding meaning you can amp up but you can let go",
	"19_2": "and I call it returned to Baseline  so that is the Baseline piece you would go through this process to increase your flexibility agility",
	"19_3": "adaptability without doing anything it's a nervous system that is just more precise and and that's what the HRV training can do 1 improve",
	"19_4": "ring Baseline 2 is what I call HRV hacking and using wearables to calibrate your Elite self so you start to collect data okay",
	"19_5": "on Tuesday I was a 42 HRV on my on my wearable but on Sunday I was a 65 what's the difference and you",
	"20_0": "begin to Target the variables and then Define the algorithm  through  your own tracking to get a sense of what really",
	"20_1": "helps calibrate you and what's so fascinating is it's different for everybody so when you when you really get to know somebody and and look at the way",
	"20_2": "live their life the way alcohol may impact you make may be completely different from your neighbor you may be someone that running 3 miles a day",
	"20_3": "really activates your parasympathetic nervous system in a beautiful way that shows up in your HRV calculation so but if you do it",
	"20_4": "how many days it drops sets so you start to really get a sense of who am I from a physiological perspective  talk to me about the resonance breathing how",
	"20_5": "works the sort of pushing at the right time on the on the bike pedal I guess so this process came about to me um",
	"21_0": "many years ago in grad school at records University pelear who  teaches at UMDNJ  was giving a presentation",
	"21_1": "about his work with Afghani vasilo and Barney vasilo that he brought from Russia they were they were working with cosmonauts in Russia when they discovered something called",
	"21_2": "residents sinus arrhythmia and it it essentially is a frequency that activates  the entire  nervous system it's",
	"21_3": "and and different what's called vagal afferent Pathways from the brain to the heart to the digestive tract and when you activate this frequency which is a",
	"21_4": "specific frequency in the body the numeric is 0.1 Hertz you activate multiple Pathways at once allowing them to to",
	"21_5": "Titan or or strengthen the homeostatic um regulatory mechanisms  sure um",
	"22_0": "of short succinct way it he was using this at Ruckers and with the vilos to treat a multitude of health conditions with Incredible outcome",
	"22_1": "depression PTSD find 1 myalgia asthma and so I I went up to Dr Leo and I said have you used this with athletes",
	"22_2": "I I  am interested in Elite Performance and and that question led to the last 2 Decades of",
	"22_3": "my research and practice and what we found is that specifically for athletes this allows them to gain control",
	"22_4": "over anxiety and and being able to perform at what I call their full autonomic bandwidth or their Elite self and and so the",
	"22_5": "future of retraining  it takes approximately 10 weeks meeting once per week and identifying a rate of breathing that optimizes those beautiful heart rate oscillations",
	"23_0": "I have you practice that 15 minutes twice a day the first 4 weeks we worked to maximize your Baseline heart rate variability and and",
	"23_1": "I look for What's called the bearer reflex gain the the indication around week 4 that your homeostatic mechanisms that control how you respond in the moment",
	"23_2": "how you anticipate a stressful moment and how you recover from a stressor or are going to to increase and that's the first sign and then sessions",
	"23_3": "5 through 10 I walk you through my protocol for managing stress more in the moment and and being able to oscillate from a sympathetic to a Paras",
	"23_4": "pathetic state and becoming aware of when you're in each of those States so for people let's say at the Olympics they want to be able to create",
	"23_5": "create that parasympathetic State on demand and a certain number of breaths we do that a decision maker for the UN will want to make sure that he",
	"24_0": "or she is in a parasympathetic open agile receptive state where they can be very focused or contextually driven and they will",
	"24_1": "want to learn how to reliably enter  what you could call a flow state but I would scientifically call a parasympathetic state so",
	"24_2": "I I tailor the training based on the needs of the individual but it is some modulation of physiological states to then control behavioral outcomes and even how",
	"24_3": "feel  okay so  as far as I'm aware about your process there is a particular breath rate between  5",
	"24_4": "something in 6 point something yeah so it's it's generally between 5 breaths per minute and 6.5 breaths per minute cool so there is a particular rate",
	"24_5": "which is indivi its individual for each person when you find that that helps based on the rate at which your heart beats and the way that it beats",
	"25_0": "the breathing in and the breathing out at that particular Pace can help to amplify or getting it wrong to make worse your HRV you're suggesting 15 minutes in the morning and 15 minutes at the",
	"25_1": "evening so twice a day and the first 4 weeks is you trying to basically dial in what is that particular breath rate and then we sort of move forward from",
	"25_2": " so so almost at that that was great and and and I love that explanation so generally in the first session",
	"25_3": "we identify resonant frequency that rate between 5 to 6.5 uh breasts per minute and um then we do",
	"25_4": "a little a little extra fixing on the side and helping to to breathe from the abdomen on the breath um and  also",
	"25_5": "than learning to be able to  inhibit other thoughts and so there are pieces of this that I've I tailor in and I talked a little bit",
	"26_0": "uh about in my book but to activate the prefrontal lobe and 1 of the pieces since we're talking about HRV and the brain a bit today",
	"26_1": "is to make sure to use the Pacer that sets your resonant frequency if you close your eyes or listen to music you won't have the same cognitive effects when you look at a",
	"26_2": "okay sir matching your breathing  to the Pacer it's a 2 for 1 a little bit because you're optimizing oxygen and blood flow all over the body especially",
	"26_3": "to the prefrontal Level Training attention so it's maximizing the the cognitive enhancements a Pacer is just some sort of cue maybe on a",
	"26_4": "screen something like that right  and there's several different ones on the iPhone and the Android if you just type in breath Pacer you can find the 1 you prefer somewhere just a line going up and down",
	"26_5": "summer Falls that expand and contract I have an um an app on an elite HRV that walks you through my 10-week protocol you're welcome to use that",
	"27_0": "if you like there's many but that watching the Pacer as you do your practice 15 minutes twice a day does make a difference in terms of the cognitive impact",
	"27_1": "okay so you have this 15 minutes twice a day is the assumption  from you methodologically that those 15 minutes",
	"27_2": "sessions will begin to bleed into your breath rate outside of that session getting closer to that how long does it take",
	"27_3": "because I breathe at whatever rate I breathe at 6.8 breaths per minute throughout the day on average uh how long does it take to do 2 15 minute sessions a data basically",
	"27_4": "reprogram my breath rate that seems like a very big change to come from only 30 minutes a day  so it does and you're absolutely right it does",
	"27_5": "become your habit but what I'm really targeting is training your heart  so so that the rhythms the resonant frequency rhythms are going",
	"28_0": "to be different when you breathe let's say that first week at resonant frequency versus just your natural Baseline but I want The rhythms from your resonant frequency to be your Baseline",
	"28_1": "and the heart is a muscle breath rhythms or or heart rhythms heart rhythms okay so you're training the heart more than you're training the breath",
	"28_2": "during these 50-minute sessions is that right correct and subsequently you train the breath after 7 to 8 weeks but first and foremost you train the heart and by week 4",
	"28_3": "I start to see the heart pattern that we that I teach breathing at resonant frequency to begin occurring just at their Baseline",
	"28_4": "that's interesting so how long or how much work is required after going through your protocol of 10 12 weeks",
	"28_5": "how much work is made is required to maintain those gains afterward if I stop after 10 weeks do I just go back to normal  so",
	"29_0": "you have to you still have to do some breathing not the not the same level and what I recommend is to breathe 3 to 4",
	"29_1": "times a week at least for 15 minutes so it's it's kind of like calf raises in a sense Chris and once you get to a certain level of",
	"29_2": "of the muscle you wanted to develop you don't have to push as hard to maintain it but you do have to exercise it  people it's it's not",
	"29_3": "the perfect algorithm people will say they are fine with twice a week other people will say I just need to do once a day 5 days a week",
	"29_4": "other times I'll have people that will come back and just say you know the cognitive impact the the screen door effect where I can screen out what's not important and really focus",
	"29_5": "on what is is kind of waning after 9 months I want to just do a surge for another 10 weeks and we do so so if you",
	"30_0": "noticed the benefits minimizing then then you up it and sometimes it's less maybe it's 2 weeks ago going back to Everyday 15 minutes and you're feeling great again",
	"30_1": "and then you titrate so you don't have to breathe for the rest of your life for 15 minutes twice a day but you do have to do some breathing and I would just base it on how you're feeling and what you're needing",
	"30_2": "to maintain how should we be breathing throughout the day outside when we take it off the cushion so to speak what is your advice to your",
	"30_3": "Elite Performance clients on what they should be doing and what they learn in week whatever it was 6 to 10 or 8 to 10 yes I love that question I believe",
	"30_4": "we had everyone really understanding the powerful impacts of breathing not only on how we feel but how we make decisions and how we behave we have a very different world",
	"30_5": "and there are ways to use the breathing to enhance health and so particularly moments that bring someone anxiety and then taking",
	"31_0": "what I call a power 5 focusing just on that feeling of the crisp fresh air  through the inhale and then letting go of the fear or or the anxiety on the exhale",
	"31_1": "to reset and they can take those small intervals as needed but there are also kind of fun ways to use this to enhance functioning in other aspects",
	"31_2": "'s life uh parents might use this in terms of with their own children and and being able to flex sleep flexibly",
	"31_3": "respond to multiple children asking many needs at a time and before responding taking a power 5 or doing it with their kids altogether",
	"31_4": "and and we should talk about that physiological connectivity is real and it's really amazing um but um  finding moments",
	"31_5": "that that you either want to have more control over how you're responding and and be able to create a desired response or enhancing cognate",
	"32_0": "have functioning mental Clarity objectivity for decision making let's let's go into that explain to me uh give me a couple of protocols and also I think importantly the cues",
	"32_1": "of how people know to do the protocol um what are some of your favorites what are the ones that give the most benefit sure so  many",
	"32_2": " athletes professional athletes whether NBA or PGA Tour or notice their mind racing and it it can be even something that something great",
	"32_3": "that happens a birdie on the golf course but their mind races the sympathetic arousal sets in and and their mind is racing and so is their walk",
	"32_4": "talking from hole to Hole they're practicing their breathing counting for in 6 out to clear the mind and also return",
	"32_5": "the body to their Baseline self foreign sticks out correct and what's interesting about adding the counting Chris is you can't count and",
	"33_0": "think at the same time they require the same part of the brain so for many people the counting with the breath and this is not for the 15-minute twice a day practice that's too much",
	"33_1": "but this is for kind of epic epic of time uses to use the counting while while they're taking",
	"33_2": "a few breaths to quickly enter the desired Baseline State yeah I guess anyone that's tried to do breath counting during meditation knows that  you lose the",
	"33_3": "account when you also lose your focus it's very difficult to keep on top of that as you're going in and out it's like playing music over the top of a sound that you don't want to hear you can kind of really only hear 1 of them",
	"33_4": "the loudest sound at 1 time okay um what about so 4 and 6 out longer on the exhale  what are some cues",
	"33_5": "that you like to give people to remind them hey this is something that you need to pay attention to this is something that you haven't done yet today  so",
	"34_0": "for some people they love being able to use this on demand if they have a racing mind or a heart rate that speeds up will identify physiological response",
	"34_1": "that would necessitate using let's say the power 5 to return to Baseline there are other people that that just want to use this during the day to",
	"34_2": "keep them calibrated without any specific need and so we'll do things like set their phone and to to vibrate at 3 different points during the day just",
	"34_3": "so they can have a quick reminder to take 5 resident press and recalibrate in other instances I like to pair it with habits for people let's say eating",
	"34_4": "so before before sitting down to have breakfast or lunch or dinner um they they take a moment to Take 5 breaths and it doesn't have to be eating but it can be some",
	"34_5": "other regular activity so that so that this becomes a way not just to bookends at the start and end of every day but a way to say calibrated",
	"35_0": "and open and engaged with the world without kind of the energetic expenses of the world coming at them  nasal breathing ever since James nest",
	"35_1": "wrote uh breath fantastic book he came on the show to talk about it nasal breathing is kind of another hot new girl in school at the moment what has your",
	"35_2": "research showed about the impact of nasal breathing on HRV and what do you see as being the best uh  facial",
	"35_3": "strategy when it comes to maximizing HRV training through breath  interesting and I've had many clients",
	"35_4": "who've read James nester's book and and they have so much difference for his work um and and we evaluate and I've had a few instances",
	"35_5": "is where the nasal breathing has  shown over the what I call the perception where you inhale through the nose but exhale through the mouth",
	"36_0": "North maximize their HRV but in most instances that's not what I've seen  and and in more instances than not the inhale through",
	"36_1": "the nose and the exhale through the nose the mouth leads to increases in HIV  when we test it in the moment",
	"36_2": "um I've also had people specifically say well I feel better 1 way or another and and I'm going to refer to the person I don't believe",
	"36_3": "leave Chris that there is a 1 size fits all and they I very much honor when someone says this makes me feel this way then then I'm going to defer to",
	"36_4": "and we're going to work with it so what's interesting I don't have my clients take a pause at the top of their breath before they exhale but every once in a while I'll say it someone will say",
	"36_5": "I need that part so so we incorporate it and and there's just nuances for everyone's nervous system so just succinctly to answer your question I have not",
	"37_0": "seen uh that the nasal breathing produces  HRV gains that are  um more than the inhale through the nose and the",
	"37_1": "exhale through the mouth there is something about the inhaling through the nose and the exhaling through the mouth that increases what's called Peak expiratory flow and leads to chord",
	"37_2": "vascular effects so my endurance athletes including my golfers on the tour will say Doc at week 7 my training hasn't changed and I'm just not tired on whole 8",
	"37_3": "anymore what's happening  and um that I haven't found to happen with the nasal breathing but we certainly could explore it  who are",
	"37_4": "some of the clients that you work with what what are some of the illustrious Heights that they've got to  I've worked with NB",
	"37_5": "a coaches that  um have have done extremely well um in the NBA I have worked with",
	"38_0": "hedge fund owners PGA Tour players at the Masters Olympians that PR and what I love about HRV and the training",
	"38_1": "of this process is that it helps any individual maximize their Elite self and and so it it's not it's not",
	"38_2": "Sports specific or situation specific if you are an incredible and I've worked with um 1 of the top dancers at Martha Graham and",
	"38_3": "and she had incredible experience going through this training and and being able to  reduce performance anxiety and and have 1 of what she",
	"38_4": "called her best performances on stage but what I love about this is  it takes anyone and any talent and allows them to remove",
	"38_5": "move the anxiety or the fear and then consistently be able to stay at a bandwidth  of of of their maximum talent and ability",
	"39_0": "and and to be able to inhibit other factors that would detract from it um  so the the big question",
	"39_1": "that I've had since learning about your work I have a friend Yousef who went through your protocol at the start of this year and a question that both of us had in the back of our mind is",
	"39_2": "what is the relative effect of Simply training VO2 max  I increasing your Fitness versus",
	"39_3": "is resonant breathing practices  they work beautifully together and that's why you see athletes with these",
	"39_4": "incredible HIV scores and I wouldn't say 1  is better than the other but what the HRV does the VO2 max does not is develop",
	"39_5": "helping a reflex that kicks in on its own unconsciously to help you modulate stress  right what do you see as the role then",
	"40_0": "of VO2 max training um also what about the role of low and slow versus VO2 max I'm sure even",
	"40_1": "if this isn't your area of expertise you must have an awful lot of insight into this because your clients are going to come to you and they're going to say doctor do you need me to stay in zone 2 for 45 minutes a day 3 times a week",
	"40_2": "would you rather me try and get up to maximal uh sort of 90% plus heart rates for 10 minutes twice a week what do you know what's your Insight when it comes to",
	"40_3": "Fitness training for HRV improvements what does the research say  that this enhances recovery  and and it allow",
	"40_4": "those for the heart rate to stay lower for activities during no no no no no so in terms of Protocols of training",
	"40_5": "if somebody was to do a physical training uh protocol what do you tend to suggest to your clients are you saying I want you to focus more on Zone 2 I want you to focus more on your V2 Max",
	"41_0": "work from a physical perspective what do you what do you tend to advise  that's not a  an area of training that I incorporate sometimes I work with athletic training",
	"41_1": "containers and we'll compare data and and our goal is to collaboratively seem to be integrate for specific outcome um",
	"41_2": "have you ever is there any learnings that you've taken away from that are there any uh particular protocols that you've found where you go wow this seems to reliably improve",
	"41_3": "Javi from a training perspective  that's  a great question I I've had some I'll tell you some trainings",
	"41_4": "yes some kind of unexpected  um  data Collections and and so forth so um",
	"41_5": "sometimes I will see that running for specific individuals for a specific distance has an incredible impact on their HIV not all",
	"42_0": "and and sometimes it's it's I've seen that with swimming as well and um  the amount the distance",
	"42_1": "1 is really interesting because for 1 person it's 3 miles in for another it's 6 and and and binding  what distance and what frequent",
	"42_2": "and measuring it with HRV um can be really insightful the kind of unexpected ones I've seen acupuncture",
	"42_3": "improve HRV I'm also and this is kind of a funny 1 but um I've seen 2 people actors  that don't know each other",
	"42_4": "come from energy healing and and they shove up my office and and on both of those occasions and and throughout their training I I can't say what was happening again",
	"42_5": "and it didn't improve their Baseline but when they came directly from that session I could see in the moment that their HRV was uniquely higher",
	"43_0": "the normal on their parasympathetic State more easy to access  um there I've also seen people take supplements that augment",
	"43_1": "HRV what are some of those  I have no affiliation with it but lima lima is a supplement that um",
	"43_2": "has  a scientific formula l y m a correct to to optimize it has antioxidant effect",
	"43_3": "anti-anxiety facts and to improve sleep um people take it for various reasons it's and again I have no affiliation with it but I had enough clients tell me",
	"43_4": "about it and we measured it and and I measured also their sleep um as related to HIV and we saw improvements in both so it's interesting is this supplement",
	"43_5": "or is it a laser that you put on your skin that's  separate but I can also tell you a funny story about uh light exposure which is applicable",
	"44_0": "that I've had people use different lasers I've I've had people use the verilux lamp and put it next to their computers and",
	"44_1": "I have many times more times than not also seeing how that impacts HRV so what's interesting is to use HRV as a metric to determine",
	"44_2": "recommend the effectiveness of an intervention and making changes on your autonomic nervous system HRV will reflect it and and it's a reliable measure",
	"44_3": "talk to me about what people get wrong when it comes to measuring HRV there's a million ways to do it there's lots of different wearables what are the worst and the",
	"44_4": "Falls and what are the best ways to do it  nocturnal HRV is a Fairly reliable way to measure  heart rate",
	"44_5": "variability because there's generally less movement at night and less variables impacting you but of course a measurement after a lot of drinking or eating",
	"45_0": "or specific stressors going to skew that I've had people have foot twitches and then their HIV is not reliable and so it's not perfect and",
	"45_1": "if you see abnormal numbers there's generally there's something happening with the wearable or there's a specific behavior occurring in the moment to make it an aberration",
	"45_2": "and there's no need to panic he just you want to collect data and I always say all data is good data it leads to to understanding",
	"45_3": "um the ordering can be really helpful for tracking HRV uh Elite HRV had a sensor core sensor polar",
	"45_4": "for measuring HRV in the moment is also helpful but when you're walking or talking your heart rate variability is going to change and",
	"45_5": "so 1 of the things people will see increases in HRV and Aura and they don't understand its movement related even at night if they had a really restless night of",
	"46_0": "sleeper were up and down to help children or go to the bathroom their HR HRV reading is going to be skewed  yeah that's that's 1 of the things",
	"46_1": "that I learned uh Joel Jameson has been on the show uh Brian McKenzie also been on the show um you know both of those guys are talking about 1 of the challenges",
	"46_2": "you have when wearing a lot of wearables that throughout the night they take these snapshots but these snapshots are dependent on what's sleeping position are you in are you awake or are you",
	"46_3": "not and unless you have something which is continuous whatever happened to that core sense thing  that that you guys had question I have to call Jason Moore and ask because",
	"46_4": "was very good and the way to use it was to take it as soon as you woke up in the morning and then you could reliably measure your HRV across time and and  I",
	"46_5": "have to I have to give him a call I don't know if they they ran out or yeah for the for the people that don't know there was a a fingertip HRV",
	"47_0": "sensor thing that you guys were like quite highly affiliated with at least for this is 1 of our suggested uh measurement devices and um  yeah I thought that was a great idea",
	"47_1": "couldn't get it in the UK and then by the time that I'd moved to the US it had stopped uh shipping so I think you guys suggest polar straps and a few other bits and pieces",
	"47_2": "polar is great and and has fairly High scientific reliability such that you can even publish research off of it and um it allows you to",
	"47_3": "sure HRV in the moment as well as its sleep at night so you have that optionality so I'm a I'm a big fan of the Polar you can also download it to your",
	"47_4": "phone and so I've used it with coaches and and specifically NBA players to be able to get a sense of where they're at right before a game or they",
	"47_5": "sympathetic or parasympathetic State and then we play games like how to bring your heart rate down by 5 beats and 2 breaths can you do it in 1 breath can you do it in half a breath and so",
	"48_0": "say it's it's a very simple way to increase HRV and and also to allow someone to enter into a competition",
	"48_1": "in in an ideal performance state  all the any other veal practices that you recommend or that you like",
	"48_2": "there  it's  interesting there are hosts there's something that  there are different places in New York",
	"48_3": "in California I don't know how popular it is all over the world sound baths  and and you go into a",
	"48_4": "Training Center or a spa and and they use different instruments to produce different sounds the vibrations are really fascinating because they do activate",
	"48_5": "the person pathetic nervous system and of course I've collected the data on that and and it does persist for some people for beyond the moment",
	"49_0": "um but what I really think people should understand is before trying to add all of these different interventions to increase",
	"49_1": "vagal tone or to get into a parasympathetic state or even to increase parasympathetic State at Baseline is to understand",
	"49_2": "like self and measure what really helps to calibrate their most elite self what amplifies and also detracts from them",
	"49_3": "and then what their goal is and you can even do things like well how many days of the week am I in my top 25% of HRV so if",
	"49_4": "best days are Saturday and Sunday but you're training competing making decisions Monday through Friday we have a we have mismatch problem right",
	"49_5": "um and and so that would be the where I would start for most people and then after they have a sense of their HRV range",
	"50_0": "and the variables that amplify and detract then committing to 10 weeks or 10 to 12 weeks of the HRV training breathing 15 minutes twice a day",
	"50_1": "the resonant frequency the reliability is really important your training the biggest muscle in your body your heart but without the training that stimulates the bare reflux",
	"50_2": "at that certain algorithm you don't get the results if you do exactly what I've asked the 10 weeks twice a day 15 minutes it works but I've tried I you know if",
	"50_3": "people call me from India Chris can I don't can I work with you for 10 days it doesn't work like that it's The Chronic stimulation of the barrier reflex at this rate 15 minutes",
	"50_4": "today 10 weeks to reliably increase their reflux gain and and really gain control over the modulatory mechanisms of how you",
	"50_5": "anticipate respond and recover from stress  is there such a thing as a non-responder to Resonance breathing",
	"51_0": "yes but at first and then it becomes a bit of detective work to understand why  and so",
	"51_1": "if someone is not responding to the resonant frequency breathing  then we begin to talk about what's happening in their life whether it is a",
	"51_2": "a a chronic almost paralyzing state of stress um it's a lack of recovery it's overtraining and and then we",
	"51_3": "address it and  um after we take away that variable then HRV training Works across ages",
	"51_4": "is around the world and and it's just a commitment to time and disciplined  breathing at resonant frequency that produces the",
	"51_5": "what are the most common pitfalls when someone does their HRV training let's say that someone thinks that they're a non-responder and they're going through the checklist of particular",
	"52_0": "is it that they've got their frequency wrong they've detected it wrong and they're trying to breathe at the wrong rates is it what are the uh common errors it's",
	"52_1": "it's funny it may it may surprise most people it's not breathing it the wrong way even if you breathe 2 seconds off you're still going to have salutary health",
	"52_2": "positive benefits it's the trying so hard that I have to make this perfect I have to make this time meaningful that they don't actually let go",
	"52_3": "in the moment and they put so much pressure on themselves that that they minimize the impact of the training so and I've seen that happen a few times and",
	"52_4": "and  then what I'll say is I want you to make this your spa time or playful and and I I want you to be playful about your",
	"52_5": "breathing light gentle and the more and it it it's really true the more you can enjoy it the more the benefits will find you isn't it",
	"53_0": "interesting what trying to go bottom up to  teach our nervous system that this is safe that you are okay",
	"53_1": "as you are that you can deal with this to expand that uh autonomic flexibility  so that the brain then is is given the room to be able to make better decisions and in the",
	"53_2": "excess of trying to do bottom-up training a top-down problem comes in yeah how funny yeah yeah the other condition",
	"53_3": "seen interfere with the immediate effects of hrvs PTSD and and so  if you take someone who",
	"53_4": "who has just experienced a traumatic event their body is in such a startled state it takes time but don't give up the HRV",
	"53_5": "biopic can work for you it can work for anybody that's gone through a source of trauma it's it's just sticking with it and being persistent and",
	"54_0": "sometimes in those cases I'll pair a memory of feeling safe it's not the memory the cognitive it's the feeling and so it's really interesting you can you can",
	"54_1": "to help someone access physiological imprints for many people men to leaders of huge corporations software companies",
	"54_2": "thanks I mean 1 of the most potent times people have felt safe or a sense of connection is holding their child for the first time men",
	"54_3": "as well as women and and recreating a a feeling of safety going back to an imprint that exists connecting to it on the inhale and letting go of the rest of the world",
	"54_4": "so if you're feeling stuck I would I would also add connecting to a time in your life you felt really safe connected or a sense of love and letting go of trying",
	"54_5": "so hard and and persisting with the practice it it does help everybody it just sometimes it takes just a little more time to start",
	"55_0": "hell yeah Dr Leos ladies and gentlemen where should people go they want to find out more of this they're going to follow the program  so my program for heart rate variability by your feedback",
	"55_1": "is in the book heart breathe mind it's on Amazon it's Barnes & Noble it's a local Distributors around the world um and if you want",
	"55_2": "to also connect with me my website is Dr  Leah l e a h logos l a g o s.com",
	"55_3": "I'm alright Liam I appreciate you thank you for today thank you Chris such a pleasure if you enjoyed that episode you will love a selection of the best clips from the podcast over the last couple of months and it's a",
	"55_4": "available right here  go on  give me a watch",
}
